name: consultation_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # multi language
  flutter_localizations:
    sdk: flutter

  #CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  # required for one time on_boarding page
  shared_preferences: ^2.0.6
  after_layout: ^1.1.0
  introduction_screen: ^2.1.0

  # required for state management and dependency injection(locator)
  provider: ^5.0.0
  get_it: ^7.1.3

  # required for firebase implementation
  firebase_core: ^1.3.0
  firebase_analytics: ^8.1.2

  # required for firebase authentication
  firebase_auth: ^1.4.1
  google_sign_in: ^5.0.4
  flutter_facebook_login: ^3.0.0

  # required for database
  cloud_firestore: ^2.2.2
  firebase_storage: ^8.1.3

  # required for firebase operations
  path: ^1.8.0
  file_picker: ^3.0.2+2
  image_picker: ^0.8.0+3
  intl: ^0.17.0
  timeago: ^3.1.0
  firebase_messaging: ^10.0.2
  flutter_local_notifications: ^6.0.0
  dropdownfield: ^1.0.3

  # required for design
  shimmer: ^2.0.0
  palette_generator: ^0.3.0
  keyboard_attachable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

flutter_icons:
    image_path: "assets/images/logo.png"
    android: true
    ios: true

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - lang/en.json
    - lang/tr.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700