name: consultation_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # multi language
  flutter_localizations:
    sdk: flutter

  #CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  # required for one time on_boarding page
  shared_preferences: ^2.0.5
  after_layout: ^1.1.0
  introduction_screen: ^2.1.0

  # required for state management
  provider: ^5.0.0

  # required for dependency injection(locator)
  get_it: ^7.1.3

  # required for firebase implementation
  firebase_core: ^1.1.1
  firebase_analytics: ^8.0.4

  # required for firebase authentication
  firebase_auth: ^1.1.4
  google_sign_in: ^5.0.2
  flutter_facebook_login: ^3.0.0

  # required for database
  cloud_firestore: ^2.1.0
  firebase_storage: ^8.0.6

  image_picker: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - lang/en.json
    - lang/tr.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700